# docker-compose.yml
version: "3"
services:
  backend:
    build: ./backend
    depends_on:
      - db
      - frontend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=database
    env_file:
      - .env
  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000    
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: soft
    volumes:
      - pgdata:/var/lib/postgresql/pgdata
    expose:
      - 5432
    ports:
      - 5433:5432
    env_file:
      - .env 
volumes:
  pgdata: